### PR TITLE
fix github action email

### PR DESCRIPTION
**Pull request by jetersen**
This is the proper email for github actions.

### CODE REVIEW

**Comment by eduherminio** [comment]
Awesome, thanks for the contribution!

**Comment by jetersen** [comment]
@eduherminio you may want to have a look at the github action workflow I use.
Instead of using action you could use the GitHub publish release event together with GitVersion, see here: https://github.com/Specshell/specshell.software.ndde/blob/main/.github/workflows/ci.yaml

**Comment by eduherminio** [comment]
hmm very interesting, starting the flow from the other end by creating a release, right? I'll definitely have a deeper look at it to see if it fits my needs.
A limitation I noticed after a first look is that it doesn't allow releases from branches other than the default one, but that seldom happens anyway.

**Comment by jetersen** [comment]
Very true but in a simply NuGet package you usually want a particular workflow. 
I see releasing from off default branch as an old school approach to releasing software.
Your want one source of truth, your default branch.

**Pull request merged**
